import { BehaviorSubject } from "rxjs";
import { CombineLatestWithSamples } from "./operators/CombineLatestWithSamples";
import { CombineAllSamples } from "./operators/combineAllSamples";
import { MulticastSubjectSample } from "./subjects/MulticastSubjectSample";
import { SubjectAnotherSubscriber } from "./subjects/SubjectAnotherSubscriber";
import { SubjectSamples } from "./subjects/SubjectSamples";
import { BehaviorSubjectSample } from "./subjects/BehaviorSubjectSample";
import { ReplaySubjectSample } from "./subjects/ReplaySubjectSample";
import { AsyncSubjectSample } from "./subjects/AsyncSubjectSample";
import { ConcatMapSamples } from "./operators/mapping/concatMap";
import { ConcatSample } from "./operators/mapping/concat";
import { Merge } from "./operators/mapping/merge";
import { MergeMapSample } from "./operators/mapping/mergeMap";
import { ExhaustAll } from "./operators/mapping/exhaustAll";

// CombineAllSamples.run();
// CombineLatestWithSamples.Run();
// SubjectSamples.Run();
// MulticastSubjectSample.Run();
// BehaviorSubjectSample.Run();
// ReplaySubjectSample.Run();
// AsyncSubjectSample.Run();
// SubjectSamples.voidSubject();
// ConcatMapSamples.Run();
// ConcatSample.Run();
// Merge.Run();
// MergeMapSample.Run();
ExhaustAll.Run();
